import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#3f3a54",
        "on-secondary-container": "#455367",
        "error-dim": "#4e0309",
        "on-primary": "#f8f7ff",
        "surface-container-low": "#f0f4f7",
        "surface-bright": "#f7f9fb",
        "tertiary": "#615b77",
        "primary-fixed-dim": "#c6d3ff",
        "on-primary-container": "#004ab9",
        "surface-container": "#e8eff3",
        "surface-container-lowest": "#ffffff",
        "secondary": "#526074",
        "on-surface-variant": "#566166",
        "tertiary-container": "#e3dbfd",
        "primary": "#0c56d0",
        "on-primary-fixed": "#003993",
        "on-tertiary-fixed-variant": "#5c5672",
        "on-background": "#2a3439",
        "secondary-dim": "#465468",
        "on-secondary-fixed-variant": "#4e5c71",
        "tertiary-fixed": "#e3dbfd",
        "surface-variant": "#d9e4ea",
        "surface": "#f7f9fb",
        "outline": "#717c82",
        "on-tertiary": "#fcf7ff",
        "tertiary-dim": "#554f6b",
        "inverse-surface": "#0b0f10",
        "on-secondary": "#f8f8ff",
        "surface-container-highest": "#d9e4ea",
        "on-tertiary-container": "#524c68",
        "surface-tint": "#0c56d0",
        "surface-container-high": "#e1e9ee",
        "outline-variant": "#a9b4b9",
        "inverse-on-surface": "#9a9d9f",
        "primary-dim": "#004aba",
        "on-error-container": "#752121",
        "background": "#f7f9fb",
        "secondary-container": "#d5e3fc",
        "on-primary-fixed-variant": "#0253cd",
        "primary-container": "#dae2ff",
        "secondary-fixed": "#d5e3fc",
        "tertiary-fixed-dim": "#d5cdee",
        "error": "#9f403d",
        "on-secondary-fixed": "#324053",
        "on-error": "#fff7f6",
        "surface-dim": "#cfdce3",
        "error-container": "#fe8983",
        "primary-fixed": "#dae2ff",
        "on-surface": "#2a3439",
        "inverse-primary": "#5c8bff",
        "secondary-fixed-dim": "#c7d5ed"
      },
      fontFamily: {
        "headline": ["var(--font-public-sans)"],
        "body": ["var(--font-inter)"],
        "label": ["var(--font-inter)"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
